name: Sync Personal Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal fork
        run: |
          git remote add fork https://x-access-token:${{ secrets.FORK_SYNC_TOKEN }}@github.com/alicek0/NBE9-11-3-Team05.git
          git ls-remote fork
          git push fork main --force
