name: Sync Personal Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Remove workflow files
        run: |
          rm -rf .github/workflows

      - name: Push to personal fork
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git remote add fork https://x-access-token:${{ secrets.FORK_SYNC_TOKEN }}@github.com/alicek0/NBE9-11-3-Team05.git

          git add .
          git commit -m "sync fork" || echo "No changes"

          git push fork HEAD:main --force
